apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  instanceStorePolicy: RAID0
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: var.karpenter_node_instance_profile # ← Instance profile name for Karpenter nodes
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: var.cluster_name 
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: var.cluster_name
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh var.cluster_name
