apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  # Template for nodes
  template:
    metadata:
      labels:
        intent: apps
        node-type: general-purpose
    spec:
      # Instance requirements
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]  # Change to ["spot"] for spot instances
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.small", ]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
      
      # Reference to the EC2NodeClass you just created
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
  
  # Resource limits
  limits:
    cpu: 1000
    memory: 1000Gi
  
  # Disruption settings
  # disruption:
  #   consolidationPolicy: WhenEmpty
  #   consolidateAfter: 30s
  #   expireAfter: 2160h  # 90 days
